const KEY='igs_v2_data';
const seed={products:[
{id:1,name:'Gaming PC RTX 5070',sku:'PC-5070',cat:'Datorer',price:18990,cost:14000,stock:3,min:2},
{id:2,name:'Kontorsdator i5',sku:'PC-I5',cat:'Datorer',price:7990,cost:5600,stock:6,min:2},
{id:3,name:'27" QHD-skärm',sku:'MON-27QHD',cat:'Tillbehör',price:3490,cost:2300,stock:2,min:3},
{id:4,name:'Trådlöst tangentbord',sku:'KEY-WL',cat:'Tillbehör',price:699,cost:350,stock:12,min:4}],
customers:[
{id:101,name:'Anna Andersson',email:'anna@example.com',phone:'070-111 22 33',address:'Exempelvägen 1, Stockholm'},
{id:102,name:'Erik Nilsson',email:'erik@example.com',phone:'070-222 33 44',address:'Testgatan 5, Stockholm'}],
service:[
{id:'S-1048',customerId:101,device:'ASUS ROG Gaming PC',problem:'Startar ibland inte',status:'Reparation pågår',updated:'2026-09-15',note:'Vi felsöker nätaggregat och moderkort.'},
{id:'S-1049',customerId:102,device:'Lenovo laptop',problem:'Skärmen flimrar',status:'Väntar på reservdel',updated:'2026-09-14',note:'Ny skärmkabel är beställd.'}],
orders:[],sales:[],nextCustomer:103,nextService:105};
function load(){let x=localStorage.getItem(KEY);if(!x){localStorage.setItem(KEY,JSON.stringify(seed));return structuredClone(seed)}return JSON.parse(x)}
let db=load();function save(){localStorage.setItem(KEY,JSON.stringify(db))}
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK'}).format(n);
const pageTitles={dashboard:['Översikt','Butikens kontrollpanel'],products:['Produkter & lager','Hantera sortiment och lagersaldo'],pos:['Kassa','Sälj produkter och skriv kvitto'],customers:['Kunder','Kundregister'],service:['Service','Serviceärenden och status'],orders:['Beställningar','Kundordrar och leveranser'],stats:['Statistik','Försäljning och lager'],settings:['Inställningar','Systemdata och säkerhetskopiering']};
function render(){const p=location.hash.slice(1)||'dashboard';document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#title').textContent=pageTitles[p]?.[0]||'Översikt';$('#subtitle').textContent=pageTitles[p]?.[1]||'';$('#content').innerHTML=(views[p]||views.dashboard)();bind()}
function dashboard(){let sales=db.sales.reduce((a,x)=>a+x.total,0), low=db.products.filter(x=>x.stock<=x.min).length;return `<div class="grid">
<div class="card"><div class="muted">Försäljning</div><div class="metric">${money(sales)}</div><div class="small">Registrerade demoaffärer</div></div>
<div class="card"><div class="muted">Kunder</div><div class="metric">${db.customers.length}</div><div class="small">I kundregistret</div></div>
<div class="card"><div class="muted">Aktiva serviceärenden</div><div class="metric">${db.service.filter(s=>s.status!=='Hämtad').length}</div><div class="small">Följ status i Service</div></div>
<div class="card"><div class="muted">Lågt lager</div><div class="metric">${low}</div><div class="small">Produkter vid/under miniminivå</div></div></div>
<div class="panel" style="margin-top:18px"><h2>Så fungerar kundportalen</h2><p>Kunden har en separat vy och kan bara se sina egna uppgifter. Butikens lager, inköpspriser, statistik och övriga kunder är aldrig kundens behörighet.</p><a class="btn" href="kund.html">Öppna kundportalen</a></div>`}
function products(){return `<div class="toolbar"><input id="psearch" placeholder="Sök produkt eller SKU"><button class="btn" id="addProduct">+ Ny produkt</button></div><div class="panel"><table class="table"><thead><tr><th>Produkt</th><th>SKU</th><th>Kategori</th><th>Pris</th><th>Lager</th><th></th></tr></thead><tbody>${db.products.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.sku}</td><td>${p.cat}</td><td>${money(p.price)}</td><td><span class="badge ${p.stock<=p.min?'red':'ok'}">${p.stock} st</span></td><td><button class="btn secondary editp" data-id="${p.id}">Ändra</button></td></tr>`).join('')}</tbody></table></div>`}
function customers(){return `<div class="toolbar"><input id="csearch" placeholder="Sök kund"><button class="btn" id="addCustomer">+ Ny kund</button></div><div class="panel"><table class="table"><thead><tr><th>Kund</th><th>E-post</th><th>Telefon</th><th>Service</th><th></th></tr></thead><tbody>${db.customers.map(c=>`<tr><td><b>${c.name}</b></td><td>${c.email}</td><td>${c.phone}</td><td>${db.service.filter(s=>s.customerId===c.id).length}</td><td><button class="btn secondary viewc" data-id="${c.id}">Visa</button></td></tr>`).join('')}</tbody></table></div>`}
function service(){return `<div class="toolbar"><button class="btn" id="addService">+ Nytt serviceärende</button></div><div class="panel"><table class="table"><thead><tr><th>Ärende</th><th>Kund</th><th>Enhet</th><th>Status</th><th>Uppdaterad</th><th></th></tr></thead><tbody>${db.service.map(s=>{let c=db.customers.find(x=>x.id===s.customerId);return `<tr><td><b>${s.id}</b></td><td>${c?.name||'—'}</td><td>${s.device}</td><td><span class="badge">${s.status}</span></td><td>${s.updated}</td><td><button class="btn secondary edits" data-id="${s.id}">Uppdatera</button></td></tr>`}).join('')}</tbody></table></div>`}
function orders(){return `<div class="notice"><b>Viktig arkitektur:</b> Kundportalen är byggd separat från butiksbehörigheten. För riktiga konton, synk mellan enheter och riktiga kundordrar behöver systemet kopplas till en backend/databas. Den här v2-paketet är förberett för det.</div><div class="panel"><h2>Kundordrar</h2>${db.orders.length?'<table class="table"><tr><th>Order</th><th>Kund</th><th>Status</th><th>Summa</th></tr>'+db.orders.map(o=>`<tr><td>${o.id}</td><td>${o.customer}</td><td>${o.status}</td><td>${money(o.total)}</td></tr>`).join('')+'</table>':'<p class="muted">Inga riktiga onlineordrar ännu.</p>'}</div>`}
function pos(){let cart=[];return `<div class="split"><div class="panel"><h2>Produkter</h2><div class="toolbar"><input id="possearch" placeholder="Sök"><button class="btn" id="clearcart">Töm</button></div><div id="posproducts">${db.products.map(p=>`<div class="card" style="margin-bottom:8px"><b>${p.name}</b><br><span class="muted">${money(p.price)} · ${p.stock} st</span><br><button class="btn addcart" data-id="${p.id}" style="margin-top:7px">Lägg i kassa</button></div>`).join('')}</div></div><div class="panel"><h2>Kassa</h2><div id="cart">Korgen är tom.</div><hr><button class="btn success" id="pay">Betala (DEMO)</button></div></div>`}
function stats(){let sales=db.sales.reduce((a,x)=>a+x.total,0), units=db.sales.reduce((a,x)=>a+x.items.reduce((z,i)=>z+i.qty,0),0);return `<div class="grid"><div class="card"><div class="muted">Omsättning</div><div class="metric">${money(sales)}</div></div><div class="card"><div class="muted">Sålda enheter</div><div class="metric">${units}</div></div><div class="card"><div class="muted">Lagervärde</div><div class="metric">${money(db.products.reduce((a,p)=>a+p.stock*p.cost,0))}</div></div></div>`}
function settings(){return `<div class="panel"><h2>System</h2><p>v2 förbereder separation mellan butik och kundportal.</p><button class="btn secondary" id="export">Exportera demo-data</button> <button class="btn danger" id="reset">Återställ demo</button><h3 style="margin-top:25px">För riktig drift</h3><p>Aktivera en backend med autentisering, databas, server-side behörigheter, orderflöde och säkerhetsloggning. Se README.</p></div>`}
const views={dashboard:dashboard,products,customers,service,orders,stats,settings,pos};
function modal(html){$('#modal').innerHTML=`<div class="modal-box"><button class="close" id="close">×</button>${html}</div>`;$('#modal').classList.remove('hidden');$('#close').onclick=()=>$('#modal').classList.add('hidden')}
function bind(){
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>location.hash=b.dataset.page);
$('#addProduct')?.addEventListener('click',()=>modal(`<h2>Ny produkt</h2><form class="form" id="pf"><label>Namn<input name="name" required></label><label>SKU<input name="sku" required></label><label>Kategori<input name="cat" value="Tillbehör"></label><label>Pris<input name="price" type="number" required></label><label>Inköpspris<input name="cost" type="number" value="0"></label><label>Lager<input name="stock" type="number" value="0"></label><label>Minimilager<input name="min" type="number" value="1"></label><button class="btn">Spara</button></form>`));
$('#pf')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target);db.products.push({id:Date.now(),name:f.get('name'),sku:f.get('sku'),cat:f.get('cat'),price:+f.get('price'),cost:+f.get('cost'),stock:+f.get('stock'),min:+f.get('min')});save();$('#modal').classList.add('hidden');render()});
document.querySelectorAll('.editp').forEach(b=>b.onclick=()=>{let p=db.products.find(x=>x.id==b.dataset.id);modal(`<h2>Ändra produkt</h2><form class="form" id="pe"><label>Namn<input name="name" value="${p.name}"></label><label>Pris<input name="price" type="number" value="${p.price}"></label><label>Lager<input name="stock" type="number" value="${p.stock}"></label><label>Minimilager<input name="min" type="number" value="${p.min}"></label><button class="btn">Spara</button></form>`);$('#pe').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);p.name=f.get('name');p.price=+f.get('price');p.stock=+f.get('stock');p.min=+f.get('min');save();$('#modal').classList.add('hidden');render()}});
$('#addCustomer')?.addEventListener('click',()=>modal(`<h2>Ny kund</h2><form class="form" id="cf"><label>Namn<input name="name" required></label><label>E-post<input name="email" type="email" required></label><label>Telefon<input name="phone"></label><label>Adress<input name="address"></label><button class="btn">Spara</button></form>`));
$('#cf')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target);db.customers.push({id:db.nextCustomer++,name:f.get('name'),email:f.get('email'),phone:f.get('phone'),address:f.get('address')});save();$('#modal').classList.add('hidden');render()});
document.querySelectorAll('.viewc').forEach(b=>b.onclick=()=>{let c=db.customers.find(x=>x.id==b.dataset.id), ss=db.service.filter(x=>x.customerId===c.id);modal(`<h2>${c.name}</h2><p>${c.email}<br>${c.phone}<br>${c.address}</p><h3>Service</h3>${ss.map(s=>`<p><b>${s.id}</b> – ${s.device}<br>${s.status}</p>`).join('')||'<p>Inga ärenden.</p>'}`)});
$('#addService')?.addEventListener('click',()=>modal(`<h2>Nytt serviceärende</h2><form class="form" id="sf"><label>Kund<select name="customer">${db.customers.map(c=>`<option value="${c.id}">${c.name}</option>`)}</select></label><label>Enhet<input name="device" required></label><label>Problem<textarea name="problem"></textarea></label><button class="btn">Skapa</button></form>`));
$('#sf')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target);db.service.push({id:'S-'+db.nextService++,customerId:+f.get('customer'),device:f.get('device'),problem:f.get('problem'),status:'Inlämnad',updated:new Date().toISOString().slice(0,10),note:''});save();$('#modal').classList.add('hidden');render()});
document.querySelectorAll('.edits').forEach(b=>b.onclick=()=>{let s=db.service.find(x=>x.id===b.dataset.id);modal(`<h2>${s.id}</h2><p>${s.device}<br>${s.problem}</p><form class="form" id="su"><label>Status<select name="status">${['Inlämnad','Undersökning','Väntar på reservdel','Reparation pågår','Klar','Hämtad'].map(x=>`<option ${x===s.status?'selected':''}>${x}</option>`).join('')}</select></label><label>Meddelande till kund<textarea name="note">${s.note||''}</textarea></label><button class="btn success">Uppdatera</button></form>`);$('#su').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);s.status=f.get('status');s.note=f.get('note');s.updated=new Date().toISOString().slice(0,10);save();$('#modal').classList.add('hidden');render()}});
$('#export')?.addEventListener('click',()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='igelkott-store-demo.json';a.click()});
$('#reset')?.addEventListener('click',()=>{if(confirm('Återställa demo-data?')){localStorage.removeItem(KEY);db=load();render()}});
}
window.addEventListener('hashchange',render);render();