-- Igelkott Store System v2 - backendmodell
-- Detta är en PLAN/START för en riktig databas. Kör inte detta i GitHub Pages.
-- Rekommenderade tabeller:
-- companies, users/profiles, customers, products, service_tickets,
-- orders, order_items, deliveries, payments, inventory_movements.
--
-- Behörighetsregel:
-- customer_id får endast läsas/ändras av den inloggade kunden.
-- company_id måste matcha den butik användaren tillhör.
--
-- När backend väljs kan vi skapa färdiga migrationer och policies för den plattformen.
