-- Igelkott Store System v4
-- Kör denna fil i Supabase SQL Editor efter v3.
-- Den lägger till riktiga produkter/lager och RLS.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text unique not null,
  category text,
  price numeric(12,2) not null default 0 check (price >= 0),
  purchase_price numeric(12,2) not null default 0 check (purchase_price >= 0),
  stock integer not null default 0 check (stock >= 0),
  low_stock_threshold integer not null default 2 check (low_stock_threshold >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "customers read active products" on public.products;
create policy "customers read active products"
on public.products
for select
to authenticated
using (active = true or public.is_staff());

drop policy if exists "staff insert products" on public.products;
create policy "staff insert products"
on public.products
for insert
to authenticated
with check (public.is_staff());

drop policy if exists "staff update products" on public.products;
create policy "staff update products"
on public.products
for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "staff delete products" on public.products;
create policy "staff delete products"
on public.products
for delete
to authenticated
using (public.is_staff());

grant select, insert, update, delete on public.products to authenticated;

-- Servicepris för serviceärenden.
alter table public.service_tickets
  add column if not exists price numeric(12,2) not null default 0 check (price >= 0);

grant select, insert, update on public.service_tickets to authenticated;


-- Valfritt: exempelprodukt för att testa systemet.
-- insert into public.products (name, sku, category, price, purchase_price, stock)
-- values ('Exempeldator', 'DEMO-001', 'Datorer', 7990, 6000, 3);
