-- Igelkott Store v5
-- Run this ONCE after the existing v4 schema.
-- It keeps existing customers, products and service tickets.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_no text unique not null,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'Ny' check (status in ('Ny','Bekräftad','Packas','Skickad','Klar','Avbruten')),
  payment_method text not null default 'Betala senare' check (payment_method in ('Betala senare','Swish','Kort')),
  payment_status text not null default 'Väntar' check (payment_status in ('Väntar','Betald','Misslyckad','Återbetald')),
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  discount numeric(12,2) not null default 0 check (discount >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  shipping_name text,
  shipping_address text,
  shipping_phone text,
  promo_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  sku text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text unique not null,
  discount_percent numeric(5,2) not null default 0 check (discount_percent >= 0 and discount_percent <= 100),
  active boolean not null default true,
  max_uses integer check (max_uses is null or max_uses >= 0),
  uses integer not null default 0 check (uses >= 0),
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  review_text text,
  created_at timestamptz not null default now(),
  unique(product_id, customer_id)
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.promo_codes enable row level security;
alter table public.product_reviews enable row level security;

-- Orders
drop policy if exists "customers read own orders" on public.orders;
create policy "customers read own orders" on public.orders
for select to authenticated using (customer_id = auth.uid() or public.is_staff());

drop policy if exists "customers create own orders" on public.orders;
create policy "customers create own orders" on public.orders
for insert to authenticated with check (customer_id = auth.uid());

drop policy if exists "staff update orders" on public.orders;
create policy "staff update orders" on public.orders
for update to authenticated using (public.is_staff()) with check (public.is_staff());

-- Order items
drop policy if exists "customers read own order items" on public.order_items;
create policy "customers read own order items" on public.order_items
for select to authenticated using (
  exists (select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or public.is_staff()))
);

drop policy if exists "customers create own order items" on public.order_items;
create policy "customers create own order items" on public.order_items
for insert to authenticated with check (
  exists (select 1 from public.orders o where o.id = order_id and o.customer_id = auth.uid())
);

-- Promo codes: customers can validate active codes; staff can manage.
drop policy if exists "customers read active promo codes" on public.promo_codes;
create policy "customers read active promo codes" on public.promo_codes
for select to authenticated using (active = true and (expires_at is null or expires_at > now()) or public.is_staff());

drop policy if exists "staff manage promo codes" on public.promo_codes;
create policy "staff manage promo codes" on public.promo_codes
for all to authenticated using (public.is_staff()) with check (public.is_staff());

-- Reviews
drop policy if exists "customers read reviews" on public.product_reviews;
create policy "customers read reviews" on public.product_reviews
for select to authenticated using (true);

drop policy if exists "customers create reviews" on public.product_reviews;
create policy "customers create reviews" on public.product_reviews
for insert to authenticated with check (customer_id = auth.uid());

drop policy if exists "customers update own reviews" on public.product_reviews;
create policy "customers update own reviews" on public.product_reviews
for update to authenticated using (customer_id = auth.uid()) with check (customer_id = auth.uid());

grant select, insert, update on public.orders to authenticated;
grant select, insert on public.order_items to authenticated;
grant select, insert, update, delete on public.promo_codes to authenticated;
grant select, insert, update on public.product_reviews to authenticated;

-- Seed one example promo code. Change/delete it from the admin panel if desired.
insert into public.promo_codes (code, discount_percent)
values ('IGELKOTT10', 10)
on conflict (code) do nothing;
