-- Igelkott Store System v3
-- Kör hela filen i Supabase -> SQL Editor -> New query -> Run.
-- Detta skapar riktiga kundprofiler, serviceärenden och RLS.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  phone text,
  address text,
  role text not null default 'customer' check (role in ('customer','staff','admin','owner')),
  created_at timestamptz not null default now()
);

create table if not exists public.service_tickets (
  id bigint generated by default as identity primary key,
  ticket_no text unique not null default ('S-' || floor(extract(epoch from now()))::bigint::text),
  customer_id uuid not null references public.profiles(id) on delete cascade,
  device text not null,
  problem text,
  status text not null default 'Inlämnad' check (status in ('Inlämnad','Undersökning','Väntar på reservdel','Reparation pågår','Klar','Hämtad')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id,email,full_name,phone,address)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'address'
  )
  on conflict (id) do update set email=excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('staff','admin','owner')
  );
$$;

alter table public.profiles enable row level security;
alter table public.service_tickets enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles
for select to authenticated using (id = auth.uid() or public.is_staff());

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles
for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "staff read all profiles" on public.profiles;
create policy "staff read all profiles" on public.profiles
for select to authenticated using (public.is_staff());

drop policy if exists "customer read own service" on public.service_tickets;
create policy "customer read own service" on public.service_tickets
for select to authenticated using (customer_id = auth.uid() or public.is_staff());

drop policy if exists "staff insert service" on public.service_tickets;
create policy "staff insert service" on public.service_tickets
for insert to authenticated with check (public.is_staff());

drop policy if exists "staff update service" on public.service_tickets;
create policy "staff update service" on public.service_tickets
for update to authenticated using (public.is_staff()) with check (public.is_staff());

grant select, update on public.profiles to authenticated;
grant select, insert, update on public.service_tickets to authenticated;

-- Efter att DU skapat ditt eget konto på kundsidan:
-- byt ut e-posten nedan mot ditt eget konto och kör ENDAST denna rad
-- för att göra kontot till butikens första owner.
-- update public.profiles set role='owner' where email='DIN-EPOST-HÄR';
